# Generated by Django 5.0.3 on 2024-03-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_manufactured',
            field=models.DateField(auto_now=True, verbose_name='дата изготовления'),
        ),
    ]
