# Generated by Django 5.0.3 on 2024-03-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='description_cat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_prod',
        ),
    ]
