# Generated by Django 5.0.3 on 2024-03-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='preview',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='description_cat',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_prod',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
