# Generated by Django 5.0.3 on 2024-04-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='indicates_current_version',
            field=models.BooleanField(default=True, verbose_name='признак текущей версии'),
        ),
    ]
