# Generated by Django 4.2 on 2024-05-11 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0016_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published_prod',
            field=models.BooleanField(default=False, verbose_name='публикация продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(help_text='Автор поста', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор продукта'),
        ),
    ]
