# Generated by Django 4.2 on 2024-05-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_is_published_prod_alter_product_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('publish_product', 'Can publish product'), ('describe_product', 'Can describe product'), ('change_cat_product', 'Can change category product')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
